### PR TITLE
perf: external library saves 1.2kb bytecode size

### PR DESCRIPTION
**Pull request by stevennevins**

### CODE REVIEW

**Comment by stevennevins** [comment]
lmk

**Comment by wadealexc** [comment]
I don't think we should change this in core to fix something in middleware -- maybe time for middleware to import this and adjust it on that end?

**Comment by wadealexc** [comment]
This would impact all of our core contracts (gas-wise)

**Comment by stevennevins** [comment]
Yeah the code duplication feels bad though

**Comment by stevennevins** [comment]
I ended up doing this:
[a92d51a](https://github.com/Layr-Labs/eigenlayer-middleware/pull/288/commits/a92d51acc2f09197a363761b4ede024219269cb3) where i wrap the library from core in a function that is external

**Comment by stevennevins** [comment]
@wadealexc resolved it in middleware
I ended up doing this:
[a92d51a](https://github.com/Layr-Labs/eigenlayer-middleware/pull/288/commits/a92d51acc2f09197a363761b4ede024219269cb3) where I wrap the library from core in a function that is external

**Comment by stevennevins** [comment]
@wadealexc resolved it in middleware
I ended up doing this:
[a92d51a](https://github.com/Layr-Labs/eigenlayer-middleware/pull/288/commits/a92d51acc2f09197a363761b4ede024219269cb3) where I wrap the library from core in a function that is external

**Pull request closed without merging**
