### PR TITLE
Combine flows in EP

### PR DESCRIPTION
**Pull request by Sidu28**
This PR removes the "activate restaking" pathway and intializes pods as "restaked" upon deployment.  

It also removes the "withdrawbeforerestaking" method and adds that logic to the verifyWithdrawalCredentials method that withdraws any remaining balance to the DWR before proving the withdrawal credentials.

### CODE REVIEW

**Comment by ChaoticWalrus** [comment]
> This PR removes the "activate restaking" pathway

You can't just remove this. We need to make this work for existing pod owners as well.

**Comment by Sidu28** [comment]
> > This PR removes the "activate restaking" pathway
> 
> You can't just remove this. We need to make this work for existing pod owners as well.

Now that hasRestaked = true is in the initialze() function, when we upgrade the implementation, everyone will be "restaked" right?

**Comment by ChaoticWalrus** [comment]
> Now that hasRestaked = true is in the initialze() function, when we upgrade the implementation, everyone will be "restaked" right?

No, not at all. The updated initialize function will only be called on _new_ EigenPods; the old version has already been called on existing ones!

**Comment by Sidu28** [comment]
> > Now that hasRestaked = true is in the initialze() function, when we upgrade the implementation, everyone will be "restaked" right?
> 
> No, not at all. The updated initialize function will only be called on _new_ EigenPods; the old version has already been called on existing ones!

Ah I see, didn't know that.  Opened a new PR [here](https://github.com/Layr-Labs/eigenlayer-contracts/pull/199)

**Pull request closed without merging**
