### PR TITLE
Small gas optimization

### PR DESCRIPTION
**Pull request by haythemsellami**
- Use `token` passed as arg instead of reading from storage (One less SLOAD)
- Check if staker is delegator before calling to increase delegate shares

### CODE REVIEW

**Comment by haythemsellami** [comment]
Added another commit, to check if staker delegated to an operator before calling the `increaseDelegatedShares()`

**Comment by ChaoticWalrus** [comment]
First commit seems like a decent change, thanks for the PR. Timing isn't the best with our planned audit/release schedule but we can consider for future inclusion 👍 
I think the latter change you added is redundant, but we could clarify the behavior in the future, or perhaps rename the function something like `increaseDelegatedSharesIfDelegated`, or add this change as a redundant 'safety' measure.

**Comment by haythemsellami** [comment]
> First commit seems like a decent change, thanks for the PR. Timing isn't the best with our planned audit/release schedule but we can consider for future inclusion 👍 I think the latter change you added is redundant, but we could clarify the behavior in the future, or perhaps rename the function something like `increaseDelegatedSharesIfDelegated`, or add this change as a redundant 'safety' measure.

Yeah that make sense. For the `increaseDelegatedShares()`, I think checking if staker is a delegator before calling the functions is a little bit gas efficient, but yeah maybe it is not that super important. Other than that, I guess it is better to either rename the function or only call it when it will for sure update the contract state (update the operator shares).

**Comment by ChaoticWalrus** [comment]
Closing this out due to staleness. Still really appreciate you submitting the PR and discussing it though!

**Pull request closed without merging**
