### PR TITLE
feat: add m2-mainnet-fixes to m2-mainnet

### PR DESCRIPTION
**Pull request by wadealexc**

### CODE REVIEW

**Comment by wadealexc** [comment]
We have merge conflicts -- how can we resolve those? Can we rebase? Not sure how to pull this off with the branch protection rules

**Comment by ChaoticWalrus** [comment]
> have merge conflicts -- how can we resolve those? Can we rebase? Not sure how to pull this off with the branch protection rules

potentially remove the branch protection rules briefly to do the rebase?
otherwise maybe you can:

1. branch off of `m2-mainnet`
2. rebase vs `m2-mainnet-fixes` _on the new branch_
3. make a PR from new branch to `m2-mainnet`

idk if that would actually work, but I think it might, at least?

**Comment by wadealexc** [comment]
> potentially remove the branch protection rules briefly to do the rebase?

opted to do this because it seemed the least hard to screw up. looking at the diff above, i think it went well :)

**Review by ChaoticWalrus — APPROVED** [review]
LGTM; thanks for sorting out the rebase!

**Pull request merged**
