### PR TITLE
Create before/after Operator Registeration Hooks for StakeRegistry

### PR DESCRIPTION
**Pull request by stevennevins**

### CODE REVIEW

**Review by ChaoticWalrus — APPROVED** [review]
LGTM. Feels perhaps a little odd that the `operator` address is an input when registering but not when deregistering, but that's a separate issue from this PR

**Comment by stevennevins** [comment]
> LGTM. Feels perhaps a little odd that the `operator` address is an input when registering but not when deregistering, but that's a separate issue from this PR

Yeah agree on this point

**Comment by ChaoticWalrus** [comment]
I think this should probably just get merged? Not sure if waiting for further review.

**Comment by gpsanant** [comment]
> I think this should probably just get merged? Not sure if waiting for further review.

@stevennevins to add hooks for other registries and coordinator

**Comment by stevennevins** [comment]
@gpsanant

**Comment by stevennevins** [comment]
@gpsanant bumping for review here

**Review by gpsanant — APPROVED** [review]
lgtm

**Pull request merged**
