### PR TITLE
add shares getter in IStrategy.sol

### PR DESCRIPTION
**Pull request by daweth**
Added the shares() view function to the strategy interface, only the userUnderlying() method exists currently.

### CODE REVIEW

**Comment by ChaoticWalrus** [comment]
Seems like a good suggestion. I'm generally hesitant to add functions to interfaces, but I think it's reasonable + the existing Strategy contracts already support this.
Any opinions here @gpsanant ?

**Comment by gpsanant** [comment]
> Any opinions here @gpsanant ?

Fine by me! What's wrong with the CI? @ChaoticWalrus

**Comment by ChaoticWalrus** [comment]
> Fine by me! What's wrong with the CI? @ChaoticWalrus

OK, will approve + merge.

CI doesn't get access to GitHub secrets even when manually approved to run -- I think even for foundry tests, it's missing some necessary environment variable(s)? Definitely something we should sort out!
To be fair, this is "safer" in that it prevents leaking secrets.

**Review by ChaoticWalrus — APPROVED** [review]
LGTM, thanks for the submission.

**Pull request merged**
